name: openring_v1
description: Desktop companion app for Colmi-compatible smart rings.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  universal_ble: ^1.0.0
  flutter_riverpod: ^2.0.0
  window_manager: ^0.5.0
  system_tray: ^2.0.3
  hotkey_manager: ^0.2.3
  shared_preferences: ^2.2.0
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: ^1.9.0
  fl_chart: ^1.2.0
  drift_db_viewer: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  drift_dev: ^2.22.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.ico
